### PR TITLE
Update URL in gemspec and travis

### PR DESCRIPTION
**Pull request by lzap**
This is just an URL change and authorship in README.

### CODE REVIEW

**Comment by lzap** [comment]
@sandfoxme I will assume you still can do reviews or advice. If you don't show up for few days I will ask colleagues to do the review for me. Thanks!

**Comment by sandfoxme** [comment]
@lzap not a problem

**Comment by lzap** [comment]
Thanks, I am gonna play with jenkins a bit.

**Comment by lzap** [comment]
Travis is passing now on all rubies including 2.0. I've added icon into the README and deleted the two icons, one of them was broken and the other one was just a link to rubygems.org.

**Pull request merged**
