### PR TITLE
Fix arguments error with ruby 3

### PR DESCRIPTION
**Pull request by alexandermeindl**
We use this gem with Redmine. Redmine supports ruby 3 (maybe foreman supports it, too).

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Thanks I will push out a new minor version release. It's been a while, will bump minimum Ruby version to 2.5 is that okay for you?

**Comment by lzap** [comment]
4d5cafb..fafb783

Successfully registered gem: journald-logger (3.1.0)

**Comment by lzap** [comment]
And no, Foreman is not on Ruby 3.x yet.

**Comment by alexandermeindl** [comment]
Hi, thanks for merging! Ruby 2.5 is ok as minimum requirement for me.

**Pull request merged**
