### PR TITLE
Do not override Ruby send method

### PR DESCRIPTION
**Pull request by lzap**
This breaks the contract of Ruby logging, the change if accepted into
the mainline will require major version bump.

### CODE REVIEW

**Comment by sandfoxme** [comment]
@lzap send is a public method described in the documentation. It will require a version bump to 3.0.0

**Comment by sandfoxme** [comment]
ignore me, I haven't read the whole commit :D

**Comment by lzap** [comment]
Won't ignore you, Anton :-) Please do review the change if you like it, not going to merge anything without your blessing. I will test it of course myself, but first the discussion around to merge or to keep it.

**Comment by sandfoxme** [comment]
Ok, what I meant was ignore that comment

I approve, just please add a change to the CHANGELOG

**Comment by lzap** [comment]
Successfully registered gem: journald-logger (3.0.0)

**Pull request merged**
